version: '2'

services:
  postgres:
    restart: always
    image: postgres:11.6
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  redis:
    image: "redis:alpine"

  celery:
    build: .
    container_name: celery
    command: celery -A django_rolls worker -l info
    environment:
      - DJANGO_SECRET_KEY=local
    volumes:
      - ./:/code
    depends_on:
      - web
      - postgres
      - redis
  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A django_rolls beat -l info
    environment:
      - DJANGO_SECRET_KEY=local
    volumes:
      - ./:/code
    depends_on:
      - web
      - postgres
      - redis

volumes:
  app-db-data:
